### ISSUE TITLE
How do I request a verification code?

### ISSUE THREAD

**Issue by sehgal15** [aic-factcheck/fact_checking_be#10]
Hi, I am trying to setup this on my local machine. While signing up it requests for a 'Verification code'. How do I get this code?
Thanks

**Comment by rastislavkopal** [comment]
Hi,
currently there are two ways of registering a new account.
You may use `/register` API that is used for basic registration.
The other way (`/register-code` api) is to setup SMTP server that sends a new verification code via email to the email address specified when creating a new invitation.
Currently it's commented out. Buy you can uncomment this service in docker-compose.yml and specify SMTP details in .env file

**Comment by sehgal15** [comment]
Thanks, was able to create a user.
